spring:
  config:
    import:
      - optional:classpath:application-db.yml

logging:
  level:
    org:
      springframework:
        web: DEBUG
        web.reactive: DEBUG

artel:
  agent:
    base-url: ${ARTEL_AGENT_BASE_URL:http://localhost:8000}
