-- ARTEL-453: 두 관측을 같은 화면으로 볼지는 `discriminator` 가 정한다. 그 사실을
-- DB 가 강제하게 한다.
--
-- V40 의 `screen` 에는 유니크가 없었다. 화면을 만드는 코드가 없었으니 필요도 없었고, 적재기가
-- 메모리에서 같은 화면으로 볼지를 들고 있으리라는 전제로 충분했다. 이제 `pulse` 가 화면을 만들기
-- 시작하는데 그 전제가 성립하지 않는다 — `fold` 상태는 프로세스 메모리라 재시작하면 사라지고, 같은 빌드를 두
-- 서버가 동시에 관측하면 각자 자기 메모리를 본다. 그때마다 같은 화면이 행 둘로 갈리고,
-- `observed_count` 가 그 둘에 쪼개져 "몇 번 지나갔나"가 둘 다 틀린 값이 된다.
--
-- `screen_transition` 과 `scene_edge` 가 이미 같은 이유로 유니크를 들고 있다. 화면만 없었다.
--
-- jsonb 는 저장할 때 정규화된다(키 정렬·공백 제거). 그래서 같은 뜻의 `discriminator` 는 같은 값으로
-- 비교된다. 다만 **배열은 순서가 있다** — 적재기가 selector 로 정렬해 쓰지 않으면 같은 화면이
-- 다른 `discriminator` 가 되므로, 그 정렬은 여전히 코드의 책임이다(`ScreenDiscriminator`).
--
-- 유니크가 아니라 인덱스인 이유: jsonb 는 B-tree 인덱스에 들어가지만 큰 값은 페이지 한도를
-- 넘길 수 있다. `discriminator` 는 조작 가능한 객체의 selector 목록이라 실측 수십 바이트지만, 한도를
-- 넘는 게임이 나오면 INSERT 가 거절된다. 그때는 `discriminator` 가 너무 크다는 뜻이고 임계값을 고칠
-- 신호이지 인덱스를 뗄 신호가 아니다.
CREATE UNIQUE INDEX IF NOT EXISTS uk_screen_discriminator
    ON screen (scene_id, discriminator);
